#!/bin/bash

. ./installers/source-to-export-vars.sh
./installers/01-emacs-and-tools.sh
./installers/02-chemacs-setup.sh
./installers/03-clone-spacemacs-develop.sh
./installers/04-multiple-spacemacs-configs.sh
# ./installers/05-doom-setup.sh
./installers/06-prepare-tools.sh
#TODO Make alias or bin commands with tools
#./installers/07-setup-tools.sh


