(defun ulys/ess-insert-magrittr-pipe ()
  "Insert magrittr pipe at i.e. \"%>%\"."
  (interactive)
  (insert "\n  %>% "))
(defun ulys/ess-insert-right-assign-operator ()
  "Insert  \"->\"."
  (interactive)
  (insert " -> "))
(defun ulys/ess-backquote-from-dollar ()
  "Surround with backquotes form last $ till point."
  (interactive)
  (insert "`")
  (setq initial-position (point))
  (evil-find-char-to-backward 1 (string-to-char "$"))
  (insert "`")
  (goto-char (+ 1 initial-position)))
(defun ulys/ess-backquote-delete-df$ ()
  (interactive)
  (ulys/ess-backquote-from-dollar)
  (evil-find-char-to-backward 1 (string-to-char "$"))
  (setq dollar-position (point))
  (evil-backward-WORD-begin)
  (evil-sp-delete (point) dollar-position)
  (evil-find-char 1 (string-to-char "`"))
  (evil-forward-char)
  )
